-- Borramos la tabla si existía para crearla limpia con los 5 juegos
DROP TABLE VIDEOJUEGOS;

-- 1. Crear la tabla definitiva
-- ID: la base de datos asigna el valor con columna de identidad (alineado con JPA @GeneratedValue IDENTITY)
CREATE TABLE VIDEOJUEGOS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR2(255),
    PRECIO NUMBER,
    PLATAFORMA VARCHAR2(100),
    DISPONIBILIDAD NUMBER(1)
);

-- 2. Insertar los 5 videojuegos oficiales (los mismos que en H2 y Java)
INSERT INTO VIDEOJUEGOS (ID, TITULO, PRECIO, PLATAFORMA, DISPONIBILIDAD) VALUES (1, 'The Legend of Zelda: Tears of the Kingdom', 59990, 'Nintendo Switch', 1);
INSERT INTO VIDEOJUEGOS (ID, TITULO, PRECIO, PLATAFORMA, DISPONIBILIDAD) VALUES (2, 'God of War Ragnarök', 49990, 'PlayStation 5', 1);
INSERT INTO VIDEOJUEGOS (ID, TITULO, PRECIO, PLATAFORMA, DISPONIBILIDAD) VALUES (3, 'Halo Infinite', 39990, 'Xbox Series X|S', 0);
INSERT INTO VIDEOJUEGOS (ID, TITULO, PRECIO, PLATAFORMA, DISPONIBILIDAD) VALUES (4, 'Elden Ring', 44990, 'PC', 1);
INSERT INTO VIDEOJUEGOS (ID, TITULO, PRECIO, PLATAFORMA, DISPONIBILIDAD) VALUES (5, 'Mario Kart 8 Deluxe', 54990, 'Nintendo Switch', 1);

-- Sincronizar contador de identidad tras inserts manuales (evita colisiones en el siguiente ID autogenerado)
ALTER TABLE VIDEOJUEGOS MODIFY ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

-- 3. Confirmar cambios
COMMIT;

-- Consultar el catálogo completo de videojuegos para validar la persistencia en la nube
SELECT * FROM VIDEOJUEGOS;

-- Buscar cualquier juego que contenga la palabra 'God'
SELECT * FROM VIDEOJUEGOS WHERE TITULO LIKE '%God%';

-- Ver solo los juegos que son de Nintendo Switch
SELECT * FROM VIDEOJUEGOS WHERE PLATAFORMA = 'Nintendo Switch';

-- Listar juegos que NO están disponibles (donde disponibilidad es 0)
SELECT * FROM VIDEOJUEGOS WHERE DISPONIBILIDAD = 0;

-- Listar todos los juegos ordenados del más caro al más barato
SELECT * FROM VIDEOJUEGOS ORDER BY PRECIO DESC;

-- Saber cuántos juegos tienes por cada plataforma
SELECT PLATAFORMA, COUNT(*) AS TOTAL_JUEGOS 
FROM VIDEOJUEGOS 
GROUP BY PLATAFORMA;

SELECT * FROM VIDEOJUEGOS;